language: swift
matrix:
    include:
        - osx_image: xcode11.4.1

before_install:
#   - echo "git \"file://$($(dirname $0); pwd)\"" >> Cartfile
#   - cat Cartfile
    - rm -f .ruby-version
    - brew update
    - brew outdated swiftlint || brew upgrade swiftlint
#   - carthage update --platform iOS

script:
    - xcodebuild -scheme AKProcessIndicator -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro' -configuration Debug test | xcpretty -c
    - swiftlint

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 32f86711-302e-4fa6-bf17-d5cf3efc60c1

# https://docs.travis-ci.com/user/reference/osx/#xcode-version
# https://docs.travis-ci.com/user/languages/objective-c/

